entries:
- database: MARKETING_PROD
  name: RAW_CAMPAIGNS_SCH
- database: MARKETING_DEV
  name: RAW_CAMPAIGNS_SCH
- database: MARKETING_QA
  name: RAW_CAMPAIGNS_SCH
- database: MARKETING_PROD
  name: SOCIAL_MEDIA_SCH
- database: MARKETING_DEV
  name: SOCIAL_MEDIA_SCH
- database: MARKETING_QA
  name: SOCIAL_MEDIA_SCH
- database: MARKETING_PROD
  name: LEADS
- database: MARKETING_DEV
  name: LEADS
- database: MARKETING_QA
  name: LEADS
