entries:
- database: FINANCE_PROD
  name: RAW_SCH
- database: FINANCE_DEV
  name: RAW_SCH
- database: FINANCE_QA
  name: RAW_SCH
- database: FINANCE_DEV
  name: CURATED_SCH
- database: FINANCE_PROD
  name: CURATED_SCH
