entries:
- database: FINANCE_PROD
  name: COMPLIANCE_SCH
- database: FINANCE_DEV
  name: COMPLIANCE_SCH
- database: FINANCE_QA
  name: COMPLIANCE_SCH
- database: FINANCE_PROD
  name: TALENT_MANAGEMENT_SCH
- database: FINANCE_DEV
  name: TALENT_MANAGEMENT_SCH
